export const WorkletMessageTypes = {
  INIT: 'INIT',
  SET_SUPPRESSION_LEVEL: 'SET_SUPPRESSION_LEVEL',
  SET_BYPASS: 'SET_BYPASS',
  SET_ADAPTIVE: 'SET_ADAPTIVE',
  SET_WORKER_PORT: 'SET_WORKER_PORT',
  SET_FRAME_LENGTH: 'SET_FRAME_LENGTH',
} as const;
